### ISSUE TITLE
Cant run this sample

### ISSUE THREAD

**Issue by razsaroya** [Pushwoosh/pushwoosh-react-native-sample#1]
Downloaded, npm installed, and gradlew cleaned
also i'v got all android build tools versions installed

Getting this error : 

:pushwooshplugin:processReleaseResources FAILED          
              
FAILURE: Build failed with an exception.
              
* What went wrong:
Execution failed for task ':pushwooshplugin:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\razsa\AppData\Local\Android\sdk\build-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1

**Comment by DimanAM** [comment]
Cannot reproduce this problem. It might be related to filepath length restrictions on Windows.
Try running gradle with `--info --stacktrace` options to see more detailed information about this failure.
