### ISSUE TITLE
Update the sample to reflect the plugin's updates

### ISSUE THREAD

**Issue by nicholasc** [Pushwoosh/pushwoosh-react-native-sample#4]

**Comment by wfhm** [comment]
Hey @nicholasc ,

I have put this task in our pipeline, however could you please provide us with a bit more details on your query? What exactly do you want to see updated and which changes should we cover?

Also, the sample app works just fine with the latest plugin version on my device. Does it work for you?

**Comment by nicholasc** [comment]
I wanted to see the optimal build.gradle for the most recent version to keep debugging https://github.com/Pushwoosh/pushwoosh-react-native-plugin/issues/27

**Comment by wfhm** [comment]
build.gradle is updated in the latest release.
